# Generated by Django 4.0.6 on 2022-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publico',
            field=models.BooleanField(default=True),
        ),
    ]
